# Generated by Django 4.1 on 2022-08-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del Director', max_length=64)),
                ('apellido', models.CharField(help_text='Apellido del Director', max_length=64)),
                ('nacimiento', models.DateField(help_text='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del genero', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la pelicula', max_length=64)),
                ('anio', models.DateField(help_text='Fecha de estreno')),
                ('descripcion', models.TextField(help_text='Sinopsis de la pelicula', max_length=255)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director')),
                ('genero', models.ManyToManyField(to='catalog.genre')),
            ],
        ),
    ]
